// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MycoreWebAPI.Models;

public partial class Ipl
{
    public int Teamno { get; set; }

    public string Teamname { get; set; }

    public string Captain { get; set; }

    public string Teamstate { get; set; }

    public int? Totalbudget { get; set; }
}