// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MycoreWebAPI.Models;

public partial class Winner
{
    public int Id { get; set; }

    public int? Yearplayed { get; set; }

    public string Stadium { get; set; }

    public string Winningteam { get; set; }

    public string Runnerteam { get; set; }

    public string Pom { get; set; }
}